version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: 'root'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
